import React, { Component } from 'react'
import AppBar from 'material-ui/AppBar'
import IconButton from 'material-ui/IconButton';
import Menu from 'material-ui/svg-icons/navigation/menu';
import FlatButton from 'material-ui/FlatButton';

export default class Header extends Component {

  handleClick() {
    alert('onClick triggered on the title component');
  }

  render() {
    return (
      <div style={styles.body}>
        <div></div>
        <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sodales pretium sem, non viverra dui fringilla vel. Proin ac fringilla velit, a mattis lectus. Nullam sodales enim vel commodo hendrerit. Cras pretium mi in condimentum finibus. Duis sed aliquet erat. Phasellus in tincidunt ante, id tincidunt est. Nam nec blandit velit. Nullam fringilla imperdiet mauris, bibendum rutrum sapien facilisis nec. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Cras quis nisl eget neque accumsan aliquet et id orci. Integer vestibulum dapibus mauris. Nulla vitae commodo diam.</div><br/>
        <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sodales pretium sem, non viverra dui fringilla vel. Proin ac fringilla velit, a mattis lectus. Nullam sodales enim vel commodo hendrerit. Cras pretium mi in condimentum finibus. Duis sed aliquet erat. Phasellus in tincidunt ante, id tincidunt est. Nam nec blandit velit. Nullam fringilla imperdiet mauris, bibendum rutrum sapien facilisis nec. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Cras quis nisl eget neque accumsan aliquet et id orci. Integer vestibulum dapibus mauris. Nulla vitae commodo diam.</div><br/>
        <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sodales pretium sem, non viverra dui fringilla vel. Proin ac fringilla velit, a mattis lectus. Nullam sodales enim vel commodo hendrerit. Cras pretium mi in condimentum finibus. Duis sed aliquet erat. Phasellus in tincidunt ante, id tincidunt est. Nam nec blandit velit. Nullam fringilla imperdiet mauris, bibendum rutrum sapien facilisis nec. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Cras quis nisl eget neque accumsan aliquet et id orci. Integer vestibulum dapibus mauris. Nulla vitae commodo diam.</div><br/>
        <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sodales pretium sem, non viverra dui fringilla vel. Proin ac fringilla velit, a mattis lectus. Nullam sodales enim vel commodo hendrerit. Cras pretium mi in condimentum finibus. Duis sed aliquet erat. Phasellus in tincidunt ante, id tincidunt est. Nam nec blandit velit. Nullam fringilla imperdiet mauris, bibendum rutrum sapien facilisis nec. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Cras quis nisl eget neque accumsan aliquet et id orci. Integer vestibulum dapibus mauris. Nulla vitae commodo diam.</div><br/>
        <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sodales pretium sem, non viverra dui fringilla vel. Proin ac fringilla velit, a mattis lectus. Nullam sodales enim vel commodo hendrerit. Cras pretium mi in condimentum finibus. Duis sed aliquet erat. Phasellus in tincidunt ante, id tincidunt est. Nam nec blandit velit. Nullam fringilla imperdiet mauris, bibendum rutrum sapien facilisis nec. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Cras quis nisl eget neque accumsan aliquet et id orci. Integer vestibulum dapibus mauris. Nulla vitae commodo diam.</div><br/>
        <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sodales pretium sem, non viverra dui fringilla vel. Proin ac fringilla velit, a mattis lectus. Nullam sodales enim vel commodo hendrerit. Cras pretium mi in condimentum finibus. Duis sed aliquet erat. Phasellus in tincidunt ante, id tincidunt est. Nam nec blandit velit. Nullam fringilla imperdiet mauris, bibendum rutrum sapien facilisis nec. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Cras quis nisl eget neque accumsan aliquet et id orci. Integer vestibulum dapibus mauris. Nulla vitae commodo diam.</div><br/>
        <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sodales pretium sem, non viverra dui fringilla vel. Proin ac fringilla velit, a mattis lectus. Nullam sodales enim vel commodo hendrerit. Cras pretium mi in condimentum finibus. Duis sed aliquet erat. Phasellus in tincidunt ante, id tincidunt est. Nam nec blandit velit. Nullam fringilla imperdiet mauris, bibendum rutrum sapien facilisis nec. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Cras quis nisl eget neque accumsan aliquet et id orci. Integer vestibulum dapibus mauris. Nulla vitae commodo diam.</div><br/>
        <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sodales pretium sem, non viverra dui fringilla vel. Proin ac fringilla velit, a mattis lectus. Nullam sodales enim vel commodo hendrerit. Cras pretium mi in condimentum finibus. Duis sed aliquet erat. Phasellus in tincidunt ante, id tincidunt est. Nam nec blandit velit. Nullam fringilla imperdiet mauris, bibendum rutrum sapien facilisis nec. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Cras quis nisl eget neque accumsan aliquet et id orci. Integer vestibulum dapibus mauris. Nulla vitae commodo diam.</div><br/>
        <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sodales pretium sem, non viverra dui fringilla vel. Proin ac fringilla velit, a mattis lectus. Nullam sodales enim vel commodo hendrerit. Cras pretium mi in condimentum finibus. Duis sed aliquet erat. Phasellus in tincidunt ante, id tincidunt est. Nam nec blandit velit. Nullam fringilla imperdiet mauris, bibendum rutrum sapien facilisis nec. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Cras quis nisl eget neque accumsan aliquet et id orci. Integer vestibulum dapibus mauris. Nulla vitae commodo diam.</div><br/>
        <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sodales pretium sem, non viverra dui fringilla vel. Proin ac fringilla velit, a mattis lectus. Nullam sodales enim vel commodo hendrerit. Cras pretium mi in condimentum finibus. Duis sed aliquet erat. Phasellus in tincidunt ante, id tincidunt est. Nam nec blandit velit. Nullam fringilla imperdiet mauris, bibendum rutrum sapien facilisis nec. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Cras quis nisl eget neque accumsan aliquet et id orci. Integer vestibulum dapibus mauris. Nulla vitae commodo diam.</div><br/>
        <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sodales pretium sem, non viverra dui fringilla vel. Proin ac fringilla velit, a mattis lectus. Nullam sodales enim vel commodo hendrerit. Cras pretium mi in condimentum finibus. Duis sed aliquet erat. Phasellus in tincidunt ante, id tincidunt est. Nam nec blandit velit. Nullam fringilla imperdiet mauris, bibendum rutrum sapien facilisis nec. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Cras quis nisl eget neque accumsan aliquet et id orci. Integer vestibulum dapibus mauris. Nulla vitae commodo diam.</div><br/>
        <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sodales pretium sem, non viverra dui fringilla vel. Proin ac fringilla velit, a mattis lectus. Nullam sodales enim vel commodo hendrerit. Cras pretium mi in condimentum finibus. Duis sed aliquet erat. Phasellus in tincidunt ante, id tincidunt est. Nam nec blandit velit. Nullam fringilla imperdiet mauris, bibendum rutrum sapien facilisis nec. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Cras quis nisl eget neque accumsan aliquet et id orci. Integer vestibulum dapibus mauris. Nulla vitae commodo diam.</div><br/>
        <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sodales pretium sem, non viverra dui fringilla vel. Proin ac fringilla velit, a mattis lectus. Nullam sodales enim vel commodo hendrerit. Cras pretium mi in condimentum finibus. Duis sed aliquet erat. Phasellus in tincidunt ante, id tincidunt est. Nam nec blandit velit. Nullam fringilla imperdiet mauris, bibendum rutrum sapien facilisis nec. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Cras quis nisl eget neque accumsan aliquet et id orci. Integer vestibulum dapibus mauris. Nulla vitae commodo diam.</div><br/>
        <div>dsdasdasdas</div>
      </div>
    )
  }
}

const styles = {
  body: {
    marginTop: 80
  }
}
